package tdtest;
import cpw.mods.fml.common.*;
import cpw.mods.fml.common.event.*;
import cpw.mods.fml.common.eventhandler.SubscribeEvent;
import cpw.mods.fml.common.gameevent.TickEvent;
import net.minecraft.client.Minecraft;
import net.minecraft.entity.item.EntityItem;
import net.minecraft.entity.monster.EntityZombie;
import net.minecraft.item.ItemStack;
import net.minecraft.init.Items;
import net.minecraft.network.play.client.C08PacketPlayerBlockPlacement;
import com.kentington.thaumichorizons.common.tiles.TileVortex;
import org.fentanylsolutions.thaumicdabblery.feature.planarvortex.VortexRecipes;
import org.fentanylsolutions.thaumicdabblery.feature.planarvortex.VortexFeedbackClient;
@Mod(modid="tdplanarremoteprobe",name="Planar vortex remote probe",version="1",acceptableRemoteVersions="*",dependencies="required-after:thaumicdabblery;required-after:ThaumicHorizons;after:tc4tweak;after:salisarcana")
public final class PlanarVortexRemoteProbe {
 private final PlanarVortexPageClientChecks book=new PlanarVortexPageClientChecks();
 private boolean suctionLifted,suctionAbsorbed;private int ticks,stage,wait,checks;private boolean launched,done;private int failureSounds,routineChats,openSounds,closeSounds,legacyCraftSounds;private boolean renderStateReady=true;private int renderCalls;private float lastRenderAge=-1;private final java.util.Set<String> phases=new java.util.HashSet<>();
 private void check(boolean b,String message){checks++;if(!b)throw new AssertionError(message);}
 @Mod.EventHandler public void ready(FMLLoadCompleteEvent e){FMLCommonHandler.instance().bus().register(this);net.minecraftforge.common.MinecraftForge.EVENT_BUS.register(this);final net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher dispatcher=net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.field_147556_a;final net.minecraft.client.renderer.tileentity.TileEntitySpecialRenderer original=dispatcher.func_147546_a(TileVortex.class);dispatcher.field_147559_m.put(TileVortex.class,new net.minecraft.client.renderer.tileentity.TileEntitySpecialRenderer(){public void func_147500_a(net.minecraft.tileentity.TileEntity tile,double x,double y,double z,float partial){renderCalls++;lastRenderAge=org.fentanylsolutions.thaumicdabblery.feature.planarvortex.VortexCraftingClient.age((TileVortex)tile,partial);original.func_147500_a(tile,x,y,z,partial);}});}
 @SubscribeEvent public void sound(net.minecraftforge.client.event.sound.PlaySoundEvent17 e){if(e.name.endsWith("wandfail"))failureSounds++;if(e.name.endsWith("vortex.open"))openSounds++;if(e.name.endsWith("vortex.close"))closeSounds++;if(e.name.equals("craftstart")||e.name.equals("wand"))legacyCraftSounds++;}
 @SubscribeEvent public void chat(net.minecraftforge.client.event.ClientChatReceivedEvent e){String text=e.message.func_150260_c();if(text.contains("Not enough wand vis")||text.contains("Base cost:")||text.contains("offering")||text.contains("must be stabilized"))routineChats++;}
 @SubscribeEvent public void frame(net.minecraftforge.client.event.RenderWorldLastEvent e){Minecraft mc=Minecraft.func_71410_x();if(mc.field_71441_e==null)return;net.minecraft.tileentity.TileEntity tile=mc.field_71441_e.func_147438_o(0,5,0);if(!(tile instanceof TileVortex))return;float age=org.fentanylsolutions.thaumicdabblery.feature.planarvortex.VortexCraftingClient.age((TileVortex)tile,e.partialTicks);String phase=age>=8&&age<12?"contract":age>=12&&age<15?"rays":age>=20&&age<22?"clear":age>=26&&age<30?"release":null;if(phase!=null&&phases.add(phase)){TileVortex v=(TileVortex)tile;renderStateReady&=v.clientSynced&&org.fentanylsolutions.thaumicdabblery.feature.planarvortex.VortexCrafting.ready(v)&&Math.abs(lastRenderAge-age)<.01F;System.out.println("TD_ANIMATION_FRAME "+phase+" age="+age+" synced="+v.clientSynced+" ready="+org.fentanylsolutions.thaumicdabblery.feature.planarvortex.VortexCrafting.ready(v)+" aspects="+v.aspects.size()+" count="+v.count+" rays="+org.fentanylsolutions.thaumicdabblery.Config.showVortexCraftingRays+" listed="+mc.field_71438_f.field_147598_a.contains(v)+" renderer="+net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.field_147556_a.func_147547_b(v)+" invalid="+v.func_145837_r()+" calls="+renderCalls+" lastAge="+lastRenderAge);shot(mc,"vortex-animation-"+phase+".png");}}
 private void shot(Minecraft mc,String name){net.minecraft.util.ScreenShotHelper.func_148259_a(new java.io.File("."),name,mc.field_71443_c,mc.field_71440_d,mc.func_147110_a());}
 @SubscribeEvent public void tick(TickEvent.ClientTickEvent e){if(e.phase!=TickEvent.Phase.END||done||++ticks<30)return;Minecraft mc=Minecraft.func_71410_x();mc.field_71474_y.field_82881_y=false;
  try{
   if(!launched){launched=true;cpw.mods.fml.client.FMLClientHandler.instance().connectToServerAtStartup("127.0.0.1",Integer.getInteger("td.vat.port",25671));return;}
   if(mc.field_71462_r instanceof net.minecraft.client.gui.GuiDisconnected)throw new AssertionError("Disconnected");
   if(ticks>1200)throw new AssertionError("Timeout stage="+stage);if(mc.field_71439_g==null||mc.field_71441_e==null||!(mc.field_71441_e.func_147438_o(0,5,0) instanceof TileVortex))return;
   mc.field_71439_g.field_70177_z=.3F+.12F*(float)Math.sin(ticks*.08);mc.field_71439_g.field_70125_A=1.5F+.1F*(float)Math.cos(ticks*.08);
   if(stage==4)for(Object o:mc.field_71441_e.field_72996_f)if(o instanceof EntityItem){EntityItem item=(EntityItem)o;if(item.func_92059_d().func_77973_b()==net.minecraft.item.Item.func_150898_a(net.minecraft.init.Blocks.field_150346_d)){org.fentanylsolutions.thaumicdabblery.feature.planarvortex.VortexSuction.Path path=org.fentanylsolutions.thaumicdabblery.feature.planarvortex.VortexSuction.active(item);if(path!=null){suctionLifted|=item.field_70163_u>4.7&&path.age(item)<12;suctionAbsorbed|=org.fentanylsolutions.thaumicdabblery.feature.planarvortex.VortexSuction.absorbed(item);if(path.age(item)>=6&&path.age(item)<9&&phases.add("suction"))shot(mc,"vortex-input-suction.png");}}}
   if(stage==8){if(book.tick(mc)){checks+=book.checks;System.out.println("TD_PLANAR_REMOTE_PASS checks="+checks);done=true;mc.field_71439_g.func_71165_d("/stop");mc.func_71400_g();}return;}
   if(++wait<90)return;
   if(stage==0){check(mc.func_147118_V().func_147680_a(new net.minecraft.util.ResourceLocation("thaumicdabblery:vortex.open"))!=null&&mc.func_147118_V().func_147680_a(new net.minecraft.util.ResourceLocation("thaumicdabblery:vortex.close"))!=null,"both sound assets registered on client");check(!mc.func_71356_B(),"real dedicated server");check(org.fentanylsolutions.thaumicdabblery.Config.showVortexCraftingRays==Boolean.parseBoolean(System.getProperty("td.vortex.rays","true")),"client rays preference loaded independently");check(VortexRecipes.RECIPES.size()==4,"server scripts compiled on client");mc.field_71439_g.func_71165_d("/summon Item 0.5 5.5 0.5 {Item:{id:265s,Count:5b,Damage:0s},PickupDelay:10000s}");stage++;wait=0;return;}
   if(stage==1){int remaining=0,diamonds=0;for(Object o:mc.field_71441_e.field_72996_f)if(o instanceof EntityItem){ItemStack s=((EntityItem)o).func_92059_d();if(s.func_77973_b()==Items.field_151042_j)remaining+=s.field_77994_a;if(s.func_77973_b()==Items.field_151045_i)diamonds+=s.field_77994_a;}check(remaining==1,"input remainder synchronized");check(diamonds==0,"outputs remain inside vortex");check(mc.field_71439_g.func_70694_bm()!=null,"equipped wand synchronized");mc.func_147114_u().func_147297_a(new C08PacketPlayerBlockPlacement(0,5,0,2,mc.field_71439_g.func_70694_bm(),.5f,.5f,.5f));stage++;wait=0;return;}
   if(stage==2){int count=0;for(Object o:mc.field_71441_e.field_72996_f)if(o instanceof EntityItem){ItemStack s=((EntityItem)o).func_92059_d();if(s.func_77973_b()==Items.field_151045_i){count+=s.field_77994_a;check(s.func_82833_r().equals("Void Diamond"),"retrieved item NBT synchronized");}}check(count==1,"native wand packet retrieves exactly one output");mc.func_147114_u().func_147297_a(new C08PacketPlayerBlockPlacement(0,5,0,2,mc.field_71439_g.func_70694_bm(),.5f,.5f,.5f));mc.field_71439_g.func_71165_d("/summon Item 0.5 5.5 0.5 {Item:{id:367s,Count:4b,Damage:0s},PickupDelay:10000s}");stage++;wait=0;return;}
   if(stage==3){int n=0;for(Object o:mc.field_71441_e.field_72996_f)if(o instanceof EntityZombie){check(((EntityZombie)o).func_94057_bL().equals("The Visitor"),"entity NBT synchronized");n++;}check(n==1,"one entity spawned on server without client duplicates");mc.field_71439_g.func_71165_d("/summon Item 0.5 4.4 -0.5 {Item:{id:3s,Count:1b,Damage:0s},PickupDelay:10000s}");mc.field_71439_g.func_71165_d("/summon Item 0.5 5.5 0.5 {Item:{id:357s,Count:1b,Damage:0s},PickupDelay:10000s}");stage++;wait=0;return;}
   if(stage==4){int diamonds=0,pigs=0;for(Object o:mc.field_71441_e.field_72996_f){if(o instanceof net.minecraft.entity.passive.EntityPig)pigs++;if(o instanceof EntityItem){ItemStack s=((EntityItem)o).func_92059_d();if(s.func_77973_b()==Items.field_151045_i&&!s.func_82833_r().equals("Void Diamond"))diamonds+=s.field_77994_a;}}check(diamonds==1,"instant item appears without a wand click");check(suctionLifted&&suctionAbsorbed,"client sees input lift into center and become absorbed before output");check(pigs==0,"wand creature waits");java.util.List<VortexFeedbackClient.Cost> costs=VortexFeedbackClient.visibleCosts(mc);check(costs.size()==2,"next queued cost overlay is visible");check(costs.get(0).amount==550&&costs.get(1).amount==220,"overlay includes iron cap surcharge");check(costs.get(0).missing&&costs.get(1).missing,"empty wand aspects pulse");check(VortexFeedbackClient.formatCost(550).equals("5.5")&&VortexFeedbackClient.formatCost(200).equals("2"),"cost numbers use exact vis units");check(VortexFeedbackClient.alpha(true,0)!=VortexFeedbackClient.alpha(true,5)&&VortexFeedbackClient.alpha(false,5)==1,"missing-only pulse");net.minecraft.util.MovingObjectPosition oldHit=mc.field_71476_x;mc.field_71476_x=null;check(VortexFeedbackClient.visibleCosts(mc).isEmpty(),"look away hides preview immediately");mc.field_71476_x=oldHit;int oldSlot=mc.field_71439_g.field_71071_by.field_70461_c;mc.field_71439_g.field_71071_by.field_70461_c=8;check(VortexFeedbackClient.visibleCosts(mc).isEmpty(),"putting wand away hides overlay");mc.field_71439_g.field_71071_by.field_70461_c=oldSlot;shot(mc,"vortex-cost-missing.png");mc.func_147114_u().func_147297_a(new C08PacketPlayerBlockPlacement(0,5,0,2,mc.field_71439_g.func_70694_bm(),.5f,.5f,.5f));stage++;wait=0;return;}
   if(stage==5){int pigs=0;for(Object o:mc.field_71441_e.field_72996_f)if(o instanceof net.minecraft.entity.passive.EntityPig)pigs++;check(pigs==0,"empty wand cannot release creature");check(failureSounds>0,"native failure sound received");check(routineChats==0,"failed click emits no routine chat");mc.field_71439_g.field_71071_by.field_70461_c=1;mc.func_147114_u().func_147297_a(new net.minecraft.network.play.client.C09PacketHeldItemChange(1));stage++;wait=0;return;}
   if(stage==6){java.util.List<VortexFeedbackClient.Cost> costs=VortexFeedbackClient.visibleCosts(mc);check(costs.size()==2&&costs.get(0).amount==500&&costs.get(1).amount==200,"wand switch refreshes discounted costs");check(!costs.get(0).missing&&!costs.get(1).missing,"affordable icons stay steady");shot(mc,"vortex-cost-ready.png");check(((thaumcraft.common.items.wands.ItemWandCasting)mc.field_71439_g.func_70694_bm().func_77973_b()).getVis(mc.field_71439_g.func_70694_bm(),thaumcraft.api.aspects.Aspect.AIR)==5000,"charged wand received");mc.func_147114_u().func_147297_a(new C08PacketPlayerBlockPlacement(0,5,0,2,mc.field_71439_g.func_70694_bm(),.5f,.5f,.5f));stage++;wait=0;return;}
   if(stage==7){int pigs=0;for(Object o:mc.field_71441_e.field_72996_f)if(o instanceof net.minecraft.entity.passive.EntityPig)pigs++;check(pigs==1,"paid creature synchronized");ItemStack held=mc.field_71439_g.func_70694_bm();thaumcraft.common.items.wands.ItemWandCasting wand=(thaumcraft.common.items.wands.ItemWandCasting)held.func_77973_b();check(wand.getVis(held,thaumcraft.api.aspects.Aspect.AIR)==4500&&wand.getVis(held,thaumcraft.api.aspects.Aspect.EARTH)==4800,"vis debit synchronized to client");check(VortexFeedbackClient.visibleCosts(mc).isEmpty(),"completed queue clears cost overlay");check(phases.containsAll(java.util.Arrays.asList("contract","rays","clear","release"))&&renderStateReady,"synchronized contraction, rays, clear pause and release rendering");check(openSounds>=5&&openSounds==closeSounds,"one opening and expansion sound for each completed craft");check(legacyCraftSounds==0,"old craft sounds absent on client");stage=8;wait=0;}
  }catch(Throwable t){done=true;System.out.println("TD_PLANAR_REMOTE_FAILED checks="+checks);t.printStackTrace();if(mc.field_71439_g!=null)mc.field_71439_g.func_71165_d("/stop");mc.func_71400_g();}
 }
}
