package tdtest;
import java.util.*;
import java.lang.reflect.Method;
import net.minecraft.world.WorldServer;
import net.minecraft.entity.Entity;
import net.minecraft.entity.item.EntityItem;
import net.minecraft.entity.passive.EntityPig;
import net.minecraft.entity.player.EntityPlayerMP;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.nbt.NBTTagCompound;
import net.minecraft.util.AxisAlignedBB;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.event.entity.EntityJoinWorldEvent;
import cpw.mods.fml.common.eventhandler.SubscribeEvent;
import com.kentington.thaumichorizons.common.tiles.TileVortex;
import thaumcraft.api.aspects.Aspect;
import thaumcraft.api.aspects.AspectList;
import thaumcraft.common.config.ConfigItems;
import thaumcraft.common.items.wands.ItemWandCasting;
import org.fentanylsolutions.thaumicdabblery.feature.planarvortex.VortexRecipes;
import org.fentanylsolutions.thaumicdabblery.feature.planarvortex.VortexFeedback;
import org.fentanylsolutions.thaumicdabblery.compat.modtweaker.PlanarVortexZen;
public final class PlanarVortexCompletionChecks {
 public int checks;private WorldServer w;private TileVortex vortex;private EntityPlayerMP player;private ItemStack wand;private ItemWandCasting casting;private Method craft;
 private void check(boolean value,String message){checks++;if(!value)throw new AssertionError(message);}
 private ItemStack stack(String id,int n){return new ItemStack((Item)Item.field_150901_e.func_82594_a(id),n);}
 private EntityItem offer(String id,int n)throws Exception{EntityItem e=new EntityItem(w,50.5,100.5,40.5,stack(id,n));w.func_72838_d(e);craft.invoke(vortex,e);PlanarVortexChecks.finish(vortex);return e;}
 private List<Entity> nearby(){List<Entity> live=new ArrayList<>();for(Object o:w.func_72839_b(null,AxisAlignedBB.func_72330_a(48,98,38,53,104,43)))if(!((Entity)o).field_70128_L)live.add((Entity)o);return live;}
 private List<EntityItem> items(String id){List<EntityItem> list=new ArrayList<>();for(Entity e:nearby())if(e instanceof EntityItem&&((EntityItem)e).func_92059_d().func_77973_b()==Item.field_150901_e.func_82594_a(id))list.add((EntityItem)e);return list;}
 private int pigs(){int n=0;for(Entity e:nearby())if(e instanceof EntityPig)n++;return n;}
 private void click(){vortex.onWandRightClick(w,wand,player,50,100,40,1,0);PlanarVortexChecks.finish(vortex);}
 private void clean(){for(Entity e:nearby())e.func_70106_y();vortex.items.clear();VortexRecipes.pending(vortex).clear();}
 private void script(String s)throws Exception{PlanarVortexChecks.script(PlanarVortexChecks.PREFIX+s);}
 private void invalid(Runnable r){try{r.run();throw new AssertionError("Invalid completion accepted");}catch(IllegalArgumentException expected){checks++;}}
 public static final class Cancel {boolean items;Cancel(boolean items){this.items=items;}@SubscribeEvent public void join(EntityJoinWorldEvent e){if(items?e.entity instanceof EntityItem:e.entity instanceof EntityPig)e.setCanceled(true);}}
 public void run(WorldServer world)throws Exception{
  w=world;vortex=PlanarVortexChecks.vortex(w,50,100,40);craft=TileVortex.class.getDeclaredMethod("handleVoidCrafting",EntityItem.class);craft.setAccessible(true);player=net.minecraftforge.common.util.FakePlayerFactory.getMinecraft(w);wand=new ItemStack(ConfigItems.itemWandCasting);casting=(ItemWandCasting)wand.func_77973_b();NBTTagCompound tags=new NBTTagCompound();tags.func_74778_a("cap","gold");tags.func_74778_a("rod","greatwood");wand.func_77982_d(tags);player.field_71071_by.func_70299_a(0,wand);w.field_73010_i.add(player);
  script("PlanarVortex.addItemRecipe(\"custom:instant\", <minecraft:dirt>, <minecraft:diamond>);\nPlanarVortex.setCompletion(\"custom:instant\", \"instant\");\nPlanarVortex.addItemRecipe(\"custom:loop\", <minecraft:diamond>, <minecraft:diamond> * 2);\nPlanarVortex.setCompletion(\"custom:loop\", \"instant\");\n");
  EntityItem dirt=offer("dirt",1);check(dirt.field_70128_L&&vortex.items.isEmpty()&&items("diamond").size()==1,"instant item released without wand");EntityItem output=items("diamond").get(0);for(int i=0;i<5;i++)vortex.func_145845_h();check(items("diamond").size()==1&&output.func_92059_d().field_77994_a==1,"instant output cannot feed back into vortex");
  EntityItem unmarked=new EntityItem(w,50.5,100.5,40.5,stack("diamond",2));w.func_72838_d(unmarked);check(!output.func_70289_a(unmarked)&&!unmarked.func_70289_a(output),"protected outputs cannot merge with offerings in either direction");unmarked.func_70106_y();
  NBTTagCompound itemSaved=new NBTTagCompound();output.func_70109_d(itemSaved);EntityItem loaded=new EntityItem(w);loaded.func_70020_e(itemSaved);craft.invoke(vortex,loaded);check(!loaded.field_70128_L&&loaded.func_92059_d().field_77994_a==1,"output immunity survives entity save/load");
  ItemStack picked=output.func_92059_d().func_77946_l();output.func_70106_y();EntityItem rethrown=new EntityItem(w,50.5,100.5,40.5,picked);w.func_72838_d(rethrown);craft.invoke(vortex,rethrown);PlanarVortexChecks.finish(vortex);check(rethrown.field_70128_L&&items("diamond").get(0).func_92059_d().field_77994_a==2,"picked-up and rethrown item can craft again");clean();
  script("PlanarVortex.addEntityRecipe(\"custom:pig\", <minecraft:cookie> * 2, \"Pig\", {CustomName: \"Paid Pig\"});\nPlanarVortex.setCompletion(\"custom:pig\", \"wand\", \"aer 5, terra 2\");\n");
  EntityItem cookies=offer("cookie",5);check(cookies.func_92059_d().field_77994_a==1&&VortexRecipes.pending(vortex).size()==2&&pigs()==0,"wand entity waits with complete batches queued");cookies.func_70106_y();NBTTagCompound preview=VortexFeedback.preview(vortex,wand,player);check(preview.func_74775_l("costs").func_74762_e("aer")==500&&preview.func_74775_l("missing").func_74767_n("aer"),"preview has discounted cost and missing aspect");NBTTagCompound wandBefore=(NBTTagCompound)wand.func_77978_p().func_74737_b();wand.func_77978_p().func_74778_a("cap","iron");preview=VortexFeedback.preview(vortex,wand,player);check(preview.func_74775_l("costs").func_74762_e("aer")==550&&preview.func_74775_l("costs").func_74762_e("terra")==220,"preview preserves hundredths with wand cap modifier");wand.func_77982_d(wandBefore);vortex.items.add(stack("diamond",1));check(VortexFeedback.preview(vortex,wand,player).func_82582_d(),"native free item masks later paid preview");vortex.items.clear();click();check(VortexRecipes.pending(vortex).size()==2&&pigs()==0,"empty wand cannot complete paid recipe");
  casting.storeVis(wand,Aspect.AIR,10000);preview=VortexFeedback.preview(vortex,wand,player);check(!preview.func_74775_l("missing").func_74767_n("aer")&&preview.func_74775_l("missing").func_74767_n("terra"),"only unaffordable aspect flagged");check(casting.getVis(wand,Aspect.AIR)==10000,"preview never drains wand");click();check(casting.getVis(wand,Aspect.AIR)==10000&&VortexRecipes.pending(vortex).size()==2,"missing second aspect charges nothing");casting.storeVis(wand,Aspect.EARTH,10000);
  ItemStack expected=wand.func_77946_l();AspectList cost=new AspectList().add(Aspect.AIR,5).add(Aspect.EARTH,2);check(casting.consumeAllVisCrafting(expected,player,cost,true),"reference native vis payment");click();check(VortexRecipes.pending(vortex).size()==1&&pigs()==1,"one paid batch per click");check(casting.getVis(wand,Aspect.AIR)==casting.getVis(expected,Aspect.AIR)&&casting.getVis(wand,Aspect.EARTH)==casting.getVis(expected,Aspect.EARTH),"normal crafting discounts applied exactly");for(Entity e:nearby())if(e instanceof EntityPig)check(((EntityPig)e).func_94057_bL().equals("Paid Pig"),"queued creature NBT retained");
  NBTTagCompound saved=new NBTTagCompound();vortex.func_145841_b(saved);TileVortex restored=new TileVortex();restored.func_145839_a(saved);w.func_147455_a(50,100,40,restored);vortex=restored;check(VortexRecipes.pending(vortex).size()==1,"queued entity persists through tile save/load");script("");check(VortexRecipes.RECIPES.isEmpty()&&VortexRecipes.pending(vortex).size()==1,"script removal preserves existing offering");expected=wand.func_77946_l();casting.consumeAllVisCrafting(expected,player,cost,true);click();check(pigs()==2&&VortexRecipes.pending(vortex).isEmpty(),"saved recipe completes without current script definition");check(VortexFeedback.preview(vortex,wand,player).func_82582_d(),"empty queue clears preview");check(casting.getVis(wand,Aspect.AIR)==casting.getVis(expected,Aspect.AIR),"saved vis cost remains payable after reload");clean();
  script("PlanarVortex.addEntityRecipe(\"custom:pig\", <minecraft:cookie>, \"Pig\");\nPlanarVortex.setCompletion(\"custom:pig\", \"wand\", \"aer 3\");\n");offer("cookie",1);int air=casting.getVis(wand,Aspect.AIR);Cancel cancel=new Cancel(false);MinecraftForge.EVENT_BUS.register(cancel);try{click();check(VortexRecipes.pending(vortex).size()==1&&pigs()==0&&casting.getVis(wand,Aspect.AIR)==air,"cancelled creature spawn refunds vis and retains queue");}finally{MinecraftForge.EVENT_BUS.unregister(cancel);}click();check(pigs()==1&&VortexRecipes.pending(vortex).isEmpty(),"cancelled offering can be retried");clean();
  script("PlanarVortex.addItemRecipe(\"custom:sword\", <minecraft:dirt>, <minecraft:iron_sword> * 3);\nPlanarVortex.setCompletion(\"custom:sword\", \"wand\", \"aer 2\");\n");offer("dirt",1);check(items("iron_sword").isEmpty()&&VortexRecipes.pending(vortex).size()==1,"paid item batch waits");air=casting.getVis(wand,Aspect.AIR);cancel=new Cancel(true);MinecraftForge.EVENT_BUS.register(cancel);try{click();check(VortexRecipes.pending(vortex).size()==1&&casting.getVis(wand,Aspect.AIR)==air,"cancelled item spawn refunds vis");}finally{MinecraftForge.EVENT_BUS.unregister(cancel);}expected=wand.func_77946_l();casting.consumeAllVisCrafting(expected,player,new AspectList().add(Aspect.AIR,2),true);click();check(items("iron_sword").size()==3&&VortexRecipes.pending(vortex).isEmpty(),"one click releases whole batch in legal stacks");check(casting.getVis(wand,Aspect.AIR)==casting.getVis(expected,Aspect.AIR),"one vis charge for split output batch");clean();
  script("PlanarVortex.addEntityRecipe(\"custom:free\", <minecraft:cookie>, \"Pig\");\nPlanarVortex.setCompletion(\"custom:free\", \"wand\");\n");offer("cookie",1);casting.storeVis(wand,Aspect.AIR,0);casting.storeVis(wand,Aspect.EARTH,0);vortex.cheat=false;vortex.beams=5;click();check(pigs()==0&&VortexRecipes.pending(vortex).size()==1,"unstable vortex cannot complete queued recipe");vortex.cheat=true;vortex.beams=6;click();check(pigs()==1&&VortexRecipes.pending(vortex).isEmpty(),"free wand mode works with empty wand");
  invalid(()->PlanarVortexZen.setCompletion("custom:missing","wand"));invalid(()->PlanarVortexZen.setCompletion("custom:free","bad"));invalid(()->PlanarVortexZen.setCompletion("custom:free","instant","aer 1"));invalid(()->PlanarVortexZen.setCompletion("custom:free","wand","motus 1"));invalid(()->PlanarVortexZen.setCompletion("custom:free","wand","aer -1"));invalid(()->PlanarVortexZen.setCompletion("custom:free","wand","aer 100001"));invalid(()->PlanarVortexZen.setCompletion("custom:free","wand",null));
  clean();script("");w.func_147468_f(50,100,40);w.field_73010_i.remove(player);
 }
}
